favorite = input ("What is your favorite animal? \n> ") 
why = input ("why do you like them? \n> ") 
where = input ("where do they live? \n> ") 
fun_fact = input ("how many more water packs? \n> ") 
print ("Animal survey summary")
print ("your favorite animal is \n" + favorite)
print ("you like them because they are \n" + why)
print ("They live in \n" + where)
print ("A fun fact about yoou favorite animal that\n" + where)